name: Detekt

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektMain detektTest reportMerge --continue

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/merge.sarif
